### ISSUE TITLE
Links to external sites not working

### ISSUE THREAD

**Issue by lenart** [shageman/cbra.info#3]
When clicking to links (under Sample apps for example) I get the following JS error in Safari (OS X) `Refused to display 'https://github.com/taskrabbit/rails_engines_example' in a frame because it set 'X-Frame-Options' to 'deny'.`

In Chrome it's similar:
`Refused to display 'https://github.com/shageman/the_next_big_thing' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

**Comment by soumyahooli** [comment]
I have hosted my website on google drive and forwarding the URL from third party, getting below error when trying to load external page-- 

Refused to display 'https://github.com/soumyahooli' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
